### ISSUE TITLE
Deploy to Docker container to Kubernetes cluster

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/stargate#72]
Docker containers are build on a GitHub release with a [GitHub Action](https://github.com/eddiejaoude/stargate/pull/70), next step is to deploy these to our Kubernetes cluster with a GitHub Action

- [x] Create a Kubernetes secret for the Discord token via environment variable (Sid)
- [x] Hello world Discord Bot (Eddie)
- [x] With test command to get app version (Eddie)
- [x] Docker environment to accept Discord Token `docker run -e DISCORD_BOT_TOKEN=<token> -p 3000:3000 --name stargatebot -d ghcr.io/eddiejaoude/stargate:latest` (Eddie)

This will be done on a live stream on Monday 15th at 5pm UK time in collaboration with [Sid](https://github.com/sidpalas)

**Comment by sidpalas** [comment]
Commands to create/update kubernetes secret:

```
export TMP_SECRET_YAML_FILE=secret.yaml
export TEST_SECRET=foobar
kubectl create secret generic my-secret --from-literal=TEST_SECRET=$TEST_SECRET --dry-run -o yaml > secret.yaml
kubectl apply -f secret.yaml
rm $TMP_SECRET_YAML_FILE
```

If we created directly with `kubectl create secret` there is no good way to update it. As a workaround we can generate the corresponding yaml, store it in a file, and then use `kubectl apply`

**Comment by sidpalas** [comment]
To consume secret as environment variable within the pod we can use:

```
          env:
            - name: TEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: TEST_SECRET
```
